openapi: 3.0.0
info:
  title: ETL - Data Forest API
  description: API para processamento e armazenamento de arquivos ASC
  version: 0.0.1

servers:
  - url: http://localhost:5001
    description: Servidor local

paths:
  /asc/upload:
    post:
      summary: Upload e processamento de arquivo ASC
      description: Recebe um arquivo ASC e processa os dados para armazenamento
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: ID do usuário que envia o arquivo
                filename:
                  type: string
                  description: Nome do arquivo ASC
                table_name:
                  type: string
                  description: Nome da tabela para armazenar os dados
                asc_file:
                  type: string
                  format: binary
                  description: Arquivo ASC para processamento
      responses:
        "201":
          description: Arquivo ASC processado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ASCResponse"
        "400":
          description: Parâmetros ausentes ou inválidos
        "500":
          description: Erro no processamento do arquivo

  /asc/{table_name}/{asc_id}:
    get:
      summary: Obter um arquivo ASC por ID
      description: Retorna os detalhes de um arquivo ASC armazenado no banco de dados
      parameters:
        - name: table_name
          in: path
          required: true
          schema:
            type: string
        - name: asc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Detalhes do arquivo ASC
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ASCResponse"
        "400":
          description: ID inválido
        "404":
          description: Arquivo ASC não encontrado

    delete:
      summary: Remover um arquivo ASC por ID
      description: Exclui um arquivo ASC do banco de dados
      parameters:
        - name: table_name
          in: path
          required: true
          schema:
            type: string
        - name: asc_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Arquivo ASC removido com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Arquivo ASC removido com sucesso."
        "400":
          description: ID inválido
        "404":
          description: Arquivo ASC não encontrado

  /asc/{table_name}:
    get:
      summary: Listar arquivos ASC
      description: Retorna a lista de arquivos ASC armazenados na tabela especificada
      parameters:
        - name: table_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lista de arquivos ASC
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ASCResponse"

components:
  schemas:
    ASCResponse:
      type: object
      properties:
        asc_id:
          type: string
          format: uuid
        user_id:
          type: string
        filename:
          type: string
        geometry:
          type: string
          description: Representação WKT da geometria do ASC
        rows:
          type: integer
        cols:
          type: integer
        xllcorner:
          type: number
        yllcorner:
          type: number
        cellsize:
          type: number
        nodata_value:
          type: number
